# Generated by Django 6.0.1 on 2026-01-30 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Rabat', 'Rabat'), ('Casablanca', 'Casablanca'), ('Marrakech', 'Marrakech'), ('Tanger', 'Tanger'), ('Kenitra', 'Kenitra'), ('Agadir', 'Agadir'), ('Fes', 'Fès'), ('Meknes', 'Meknès'), ('Ifrane', 'Ifrane'), ('Oujda', 'Oujda')], max_length=50)),
                ('university_nearby', models.CharField(default='Université', max_length=100)),
                ('price', models.IntegerField()),
                ('is_bills_included', models.BooleanField(default=False)),
                ('gender_preference', models.CharField(choices=[('Filles', 'Réservé aux Étudiantes (Filles)'), ('Garçons', 'Réservé aux Étudiants (Garçons)')], default='Garçons', max_length=20)),
                ('image_url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('description', models.TextField(default='Logement respectueux et calme.')),
                ('amenities', models.CharField(default='Wifi,Sécurité', max_length=300)),
                ('whatsapp_number', models.CharField(default='212600000000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='EN ATTENTE', max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.listing')),
            ],
        ),
    ]
