# Generated by Django 6.0.1 on 2026-01-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (DH)')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('type', models.CharField(choices=[('Colocation', 'Colocation'), ('Studio', 'Studio'), ('Appartement', 'Appartement'), ('Residence', 'Résidence Étudiante'), ('Chambre', "Chambre chez l'habitant")], default='Studio', max_length=50)),
                ('university_nearby', models.CharField(blank=True, max_length=200, verbose_name='Université proche')),
                ('whatsapp_number', models.CharField(default='+212600000000', max_length=20, verbose_name='WhatsApp')),
                ('image_url', models.CharField(default='https://images.unsplash.com/photo-1522708323590-d24dbb6b0267', max_length=500, verbose_name='Lien Image (URL)')),
                ('is_verified', models.BooleanField(default=False)),
                ('owner_name', models.CharField(default='Anonyme', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
