# Generated by Django 6.0.1 on 2026-01-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('house', 'number'), name='unique_room_number_per_house'),
        ),
    ]
