# Generated by Django 6.0.1 on 2026-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='gender_preference',
            field=models.CharField(choices=[('Mixte', 'Mixte'), ('Filles', 'Filles'), ('Garçons', 'Garçons')], default='Mixte', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
